---
:translized:
  :access_token: "{token}"
  :project_id: "{projectID}"
  :download:
    :path: "./translations/<locale_code>.yml"
    :file_format: yml
  :upload:
    :path: "./translations/{code}.yml"
    :language_code: "{code}"
